//Look at them carefully:
    //a) promise.resolve(): Creates a promise that is resolved with a given value:
        console.log(new Promise((resolve) => 'This is a resolved promise')); //value IS *pending* here...
        console.log(Promise.resolve('This is a resolved promise')); //value is NOT *pending* here...

    //b) promise.reject(): Creates a promise that is rejected with a given reason:
        console.log(Promise.reject('This is a rejected promise')); //value is NOT *pending* here...
            //NOTE: this will cause an annoying error message, bcz this error is not handled!